### ISSUE TITLE
Better SIGPIPE handling

### ISSUE THREAD

**Issue by twaugh** [twaugh/journal-brief#21]
Currently, SIGPIPE causes the bookmark to be updated. Output buffering means that output may have been lost, so setting the default SIGPIPE handler may be a better approach to avoid losses.

**Comment by RalphCorderoy** [comment]
I don't know if https://github.com/twaugh/journal-brief/blob/master/journal_brief/filter.py#L251 is still relevant.

**Comment by twaugh** [comment]
It's not. Thanks for spotting it.
