### ISSUE TITLE
priority: err != PRIORITY:[0,1,2,3], contrary to documentation

### ISSUE THREAD

**Issue by PorcelainMouse** [twaugh/journal-brief#39]
Documentation says that using 'priority: err' is the same as 'PRIORITY: [0,1,2,3]', but this is not the case.  According to debug log, specifying numerical priority values sets PRIORITY filter to specified values, which seems exactly right but produces no matches even when journactl shows there are such journal entries.  Specifying priority names sets filter using log_level(), which seems to match the desired journal entries.

**Comment by twaugh** [comment]
The journal documentation says that using log_level() is equivalent to setting several PRIORITY filters, which is where that comparison came from in the journal-brief documentation.

It seems that a recent systemd change altered the type expected for PRIORITY filter matches. I've updated journal-brief to match.
