### ISSUE TITLE
Cannot set multiple output formats in config file

### ISSUE THREAD

**Issue by kpfleming** [twaugh/journal-brief#43]
Looks like some inconsistency in handling of options vs. config file. If `output` is specified in config file it can have a list of entries, and the `validate_output` function validates it, but then self.config.output is left as a `list` object.

Later, in the run() function in main, an attempt to call split() on this object is made because `output` is extracted from the config instead of `outputs`. I thought there would be an easy fix here but either way I would fix it would probably change existing behavior.

**Comment by twaugh** [comment]
See what you think of the PR I just submitted for this.

**Comment by kpfleming** [comment]
That appears to be a good fix, thanks!
