### ISSUE TITLE
Exception thrown if first non-dry run does not find matching journal entries

### ISSUE THREAD

**Issue by kpfleming** [twaugh/journal-brief#47]
If the cursor file does not already exist, and if the inclusion filters result in *zero* journal entries being matched, then an exception is thrown in the LatestJournalEntries `__exit__` function because `self.cursor` is None.

**Comment by kpfleming** [comment]
I think that setting `self.cursor` to an empty string, instead of None, when the cursor file does not exist, would be sufficient.

**Comment by twaugh** [comment]
Oh, I see. I guess using an empty string is fine.

To make it faster in the case where there are no matched entries but lots of unmatched entries, we could grab the cursor from the last entry (seek_tail(), get_previous()) and store that in self.cursor as its initial value, before seeking back to the head and building the matches up.

**Comment by kpfleming** [comment]
That's a good idea. Will send a PR.
