### ISSUE TITLE
Add support for Python 3.5.x

### ISSUE THREAD

**Issue by dernasherbrezon** [twaugh/journal-brief#61]
Some recent debian distributives have python 3.5.x installed. I tried running journal-brief there and the only obstacle is this line:

https://github.com/twaugh/journal-brief/blob/master/journal_brief/cli/main.py#L228

And this

https://github.com/twaugh/journal-brief/blob/master/journal_brief/cli/main.py#L252

Just replace ```text=True``` with ```universal_newlines=True```

**Comment by kpfleming** [comment]
Python 3.5 went EoL a long time ago, this issue likely should be closed :-)
