### ISSUE TITLE
Release new version and increment version

### ISSUE THREAD

**Issue by intrigus** [twaugh/journal-brief#66]
## Problem
The README explains here how to send an email using journal-brief:
https://github.com/twaugh/journal-brief/blob/4d774709ea184fa6fcf53c6e60e473ffdeb14d59/README.md?plain=1#L186-L188

The problem is, that version [1.1.7](https://github.com/twaugh/journal-brief/releases/tag/v1.1.7) on PyPi does not contain the changes that allow this.
With 1.1.7 it fails with this exception:
```bash
error: to: unexpected 'email' keyword
  in:
to: abc

error: subject: unexpected 'email' keyword
  in:
subject: XYZ

error: from: unexpected 'email' keyword
  in:
from: ABC
```

So one HAS to clone this repo and build it themselves. But even then, it still claims that version 1.1.7 is installed, which is not true since we cloned latest master and not the v1.1.7 tag.

## Solution
1. Increment the version tag to 1.1.8 and release a new version.
or
1. Don't release a new version but highlight that only a future version/latest master supports this new format.

**Comment by twaugh** [comment]
1.1.8 released.

**Comment by intrigus** [comment]
Thank you for releasing it and all the other work that went into creating this library!
